JSS/JSS/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('JSSapp.urls')),
    path('', include('accounts.urls')),
]

JSS/JSSapp/urls.py
from django.contrib import admin
from django.urls import path
from JSSapp.views import index, create, detail, delete, update, my_index, create_comment, delete_comment

urlpatterns = [
    path('', index, name="index"),
    path('my_index/', my_index, name="my_index"),
    path('create/', create, name="create"),
    path('detail/<int:jss_id>', detail, name="detail"),
    path('delete/<int:jss_id>', delete, name="delete"),
    path('update/<int:jss_id>', update, name="update"),

    # comment
    path('create_comment/<int:jss_id>', create_comment, name="create_comment"),
    path('delete_comment/<int:jss_id>/<int:comment_id>/', delete_comment, name="delete_comment"),
]

JSS/accounts/urls.py
from django.contrib import admin
from django.urls import path
from .views import signup, MyLoginView
from django.contrib.auth.views import LogoutView

urlpatterns = [
   path('signup/', signup, name="signup"),
   path('login/', MyLoginView.as_view(), name="login"), # LoginView 클래스를 함수로 실행
   path('logout/', LogoutView.as_view(), name="logout"),
]

JSS/JSSapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Jasoseol(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    updated_at = models.DateTimeField(auto_now=True)
    # 작성자 foreign키 설정 (작성자 회원탈퇴시 작성글 자동으로 삭제 -> cascade옵션)
    # 기존 데이터에는 author가 없으므로 migrations 거부됨 -> null=True 옵션을 주거나 default값을 주면 해결
    author = models.ForeignKey(User, on_delete=models.CASCADE)

# hyosun / 1212

class Comment(models.Model):
    content = models.CharField(max_length=100)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    jasoseol = models.ForeignKey(Jasoseol, on_delete=models.CASCADE)

JSS/accounts/models.py
from django.db import models

# Create your models here.

JSS/JSSapp/forms.py
from django import forms
from .models import Jasoseol, Comment

class JssForm(forms.ModelForm):

    class Meta:
        model = Jasoseol
        fields = ('title', 'content',)
    # 폼 커스텀하기 (기본호출함수 init 활용)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].label = "제목" # title의 label값 수정
        self.fields['content'].label = "자기소개서 내용"
        self.fields['title'].widget.attrs.update({
            'class': 'jss_title', # class 속성 추가 -> css 적용
            'placeholder': '제목', # placeholder 속성 추가
        })
        self.fields['content'].widget.attrs.update({
            'class': 'jss_content_form', # class 속성 추가 -> css 적용
        })

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('content', )

JSS/JSSapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import JssForm, CommentForm
from .models import Jasoseol, Comment
from django.http import Http404
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    all_jss = Jasoseol.objects.all()
    return render(request, 'index.html', {'all_jss':all_jss})

def my_index(request):
    my_jss = Jasoseol.objects.filter(author=request.user)
    return render(request, 'index.html', {'all_jss':my_jss})

# 모델.objects.all()
# 모델.objects.get()
# 모델.objects.filter()

@login_required(login_url='/login/')
def create(request):
    # if not request.user.is_authenticated:
    #     return redirect('login')

    if request.method == "POST":
        filled_form = JssForm(request.POST)
        if filled_form.is_valid():
            temp_form = filled_form.save(commit=False)
            temp_form.author = request.user
            filled_form.save()
            return redirect('index')

    jss_form = JssForm()
    return render(request, 'create.html', {'jss_form':jss_form})

@login_required(login_url='/login/')
def detail(request, jss_id):
    # try:
    #     my_jss = Jasoseol.objects.get(pk=jss_id)
    # except:
    #     raise Http404

    my_jss = get_object_or_404(Jasoseol, pk=jss_id)
    comment_form = CommentForm()
    return render(request, 'detail.html', {'my_jss':my_jss, 'comment_form':comment_form})

def delete(request, jss_id):
    my_jss = Jasoseol.objects.get(pk=jss_id)
    if request.user == my_jss.author: # 글 작성자인경우 삭제 (url접근)
        my_jss.delete()
        return redirect('index')
    
    return PermissionDenied # 작성자가 아닌경우 403 페이지

def update(request, jss_id):
    my_jss = Jasoseol.objects.get(pk=jss_id)
    jss_form = JssForm(instance=my_jss)
    if request.method == "POST":
        updated_form = JssForm(request.POST, instance=my_jss)
        if updated_form.is_valid():
            updated_form.save()
            return redirect('index')

    return render(request, 'create.html', {'jss_form':jss_form})

def create_comment(request, jss_id):
    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            temp_form = comment_form.save(commit=False)
            temp_form.author = request.user
            temp_form.jasoseol = Jasoseol.objects.get(pk=jss_id)
            temp_form.save()
            return redirect('detail', jss_id)

def delete_comment(request, jss_id, comment_id):
    my_comment = Comment.objects.get(pk=comment_id)
    if request.user == my_comment.author:
        my_comment.delete()
        return redirect('detail', jss_id)
    else:
        raise PermissionDenied

JSS/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
# Create your views here.

def signup(request):
    regi_form = UserCreationForm()
    if request.method == "POST":
        filled_form = UserCreationForm(request.POST)
        if filled_form.is_valid():
            filled_form.save()
            return redirect('index')

    return render(request, 'signup.html',{'regi_form':regi_form})

# django 문서의 LoginView를 MyLoginView로 상속받아서 오버라이딩
class MyLoginView(LoginView):
    template_name = 'login.html'

JSS/JSSapp/templates/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" typy="text/css" href="{% static 'style.css' %}">
    <title>Document</title>
</head>

<body>
    <a class="button" href="{% url 'index' %}">
        메인페이지로
    </a>
    <div style="text-align: center;">
        <h1>자기소개서 작성</h1>
        <div class="make_jss" style="width: 500px; height: 350px; margin: 0px auto;">
            <form method="POST" action="">
                {% csrf_token %}
                {{jss_form.as_p}}
                <input class="button submit" style="background-color: rgb(0, 0, 88);" type="submit" value="제출">
            </form>

            <div class="counted_text">글자수 :</div>
        </div>
    </div>
    <script src="{% static 'count.js' %}"></script>
</body>

</html>

JSS/JSSapp/templates/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" typy="text/css" href="{% static 'style.css' %}">
    <title>자소설 닷컴</title>
</head>

<body>
    <a class="button" href="{% url 'index' %}">
        메인페이지로
    </a>
    <div class="make_jss" style="width: 90%; height: 500px; padding: 20px; margin: 30px auto;">
        <div class="article">
        <p>제목 : {{my_jss.title}}</p><hr style="border: 0.5px solid black; width: 100%;">

        <br>

        <p>{{my_jss.content}}</p>

        <br>

        <p>💜 {{my_jss.updated_at|date:"Y.m.d"}} 💜</p>
    </div>
        <div style="display: inline; ">
            {% if user == my_jss.author %}
            <a class="button_reverse" href="{% url 'update' my_jss.id %}">수정</a>
            <a class="button_reverse" href="{% url 'delete' my_jss.id %}">삭제</a>
            {% endif %}
        </div>
    </div>
    <br>
    {% if user.is_authenticated %}
    <form method="POST" action="{% url 'create_comment' my_jss.id %}">
        {% csrf_token %}
        {{comment_form}}
        <input type="submit" value="댓글작성">
    </form>
    {% endif %}

    {% for comment in my_jss.comment_set.all %}

    <p>
        💛&nbsp&nbsp {{comment.author}}&nbsp&nbsp >> &nbsp&nbsp{{comment.content}}
        {% if user == comment.author %}
        <a class="button" href="{% url 'delete_comment' my_jss.id comment.id %}">
            삭제
        </a>
        {% endif %}
    </p>

    {% endfor %}
</body>

</html>

JSS/JSSapp/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" typy="text/css" href="{% static 'style.css' %}">
    <title>JASOSEOL.COM</title>
</head>

<body>
    <h1 style="text-align: center;">JASOSEOL . COM</h1>
    <div class="nav">
        <!-- 자기소개서 필터 -->
        {% if user.is_authenticated %}
        <a class="button" href="{% url 'my_index' %}">
            내 자기소개서만 보기
        </a>

        <a class="button" href="{% url 'index' %}">
            모든 자기소개서 보기
        </a>
        {% endif %}

        <!-- 로그인 탭 -->
        {% if user.is_authenticated %}
        <a class="button" href="{% url 'logout' %}">
            로그아웃
        </a>

        &nbsp&nbsp&nbsp💛&nbsp안녕하세요! {{user}}님&nbsp💛

        {% else %}
        <a class="button" href="{% url 'signup' %}">
           회원가입
        </a>

        <a class="button" href="{% url 'login' %}">
            로그인
        </a>

        {% endif %}
    </div>

    <!-- 자기소개서 -->
        <a href="{% url 'create' %}">
            <div class="make_jss">
                <div class="plus_btn">
                    +
                </div>
            </div>
        </a>
        <br><div class="detail"></div><br>
        <div class="jss">
        {% for jss in all_jss %}
        <a href="{% url 'detail' jss.id %}">
            <div class="all_jss">
                <p>작성자 : {{ jss.author }}</p>
                <p>{{ jss.title }}</p>
                <p>{{ jss.updated_at|date:"Y.m.d" }}</p> <!-- 템플릿 필터 -->
            </div>
        </a>
        {% endfor %}
    </div>

    <script src="{% static 'click.js' %}"></script>
    <script src="{% static 'jss_click.js' %}"></script>
</body>

</html>

JSS/accounts/templates/login.html
<h1>로그인 페이지</h1>
<form method="POST">

    {% csrf_token %}
    {{form}}
    <input type="submit" value="로그인">
    
</form>

JSS/accounts/templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    
    <h1>회원가입 페이지</h1>
    <form method="POST" action="">
        {% csrf_token %}
        {{regi_form.as_p}}
        <input type="submit" value="회원가입">
    </form>
</body>

</html>